# Generated by Django 3.0.10 on 2021-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_model',
            name='point',
            field=models.IntegerField(),
        ),
    ]
